Aivoapina/imneversorry

.gitignore, README.md, imneversorry.py, valitsin.py
> luennolle vai kiltaan
> kiltaan
Some decisions are difficult. This PR adds a new feature that considers two options and picks the correct one, totally not rigged.
Credit goes to Klassik for the original ebinbot feature.
=> Add a new feature for making the most important life decisions.

valitsin.py
People are abusing the bots decision by asking the same question over and over again, until desired answer is given. No more! Make bot rigged since it knows what is best for you.
=> Make decisions rigged

db.py, imneversorry.py, initdb.py, oppija.py
Adds new feature to store definitions to certain keywords. Might be a bit broken since I didn't really test this, but what could go wrong
=> Add new command to learn and remember definitions to keywords.

db.py, imneversorry.py, initdb.py, teekkari.py, vituttaa.py
pekkauotila:
vittuilux
törkeää solvaamista
tarvii sanalistan
=> Pekkauotila

db.py, icd.txt, initdb.py, migrate_txt_files.py, teekkari.py
Vittu että python on typerä kieli.
=> added "diagnoosi" with 15000 icd-10 disease classifications for krapula

teekkari.py
Halo:
>Halo
<Halo?
Noppa:
>Noppa
<Heitit x ja y.
=> Added halo and noppa functions!

teekkari.py
GetVitun is like vituttaa function but it uses "kurkku vitun mopo" format and takes its words from Urbaanisanakirja. E.g. `Hannibal vitun villakoira` or `kurkku vitun mopo` if you are really lucky
I also changed how halo and noppa functions are called so the work with longer messages like "haloo". I also removed my unpulled function called vaihda because I thought it was pretty useless.
=> Added getVitun function

teekkari.py
haetaan se sana titlestä perkele
=> added umlauts to vitun

db.py, imneversorry.py, teekkari.py
Testing? Got nobody time for that.
":D"
=> findQuotes quotee case insensitive

teekkari.py
=> Replace 24 hour vitun cooldown with a once-a-day cooldown

imneversorry.py
adds repeating job to job queue that sends beerpong time about every 1/80000 seconds
=> Beerpong time about once every day

teekkari.py, valitsin.py
```
Alexander, [04.09.19 19:58]
hakemus hyy-vä ja tapan sut korvataan stickereillä "JEP" ja "EI KÄY"
Imneversorry, [04.09.19 19:58]
hyy-vä
````
=> hakemus hyy-vä ja tapan sut korvataan stickereillä 'JEP' ja 'EI KÄY'

imneversorry.py
Reverts Aivoapina/imneversorry#34
=> Revert "Beerpong time about once every day"

teekkari.py
=> Give bot a little bit of consciousness

db.py, imneversorry.py, initdb.py, oppija.py, tagaaja.py, valitsin.py
Adds commands /tag, /tagged, /tags and "onko pakko".
!kiitti klassik hyvistä vanhoista featureista
=> Add more old ebinbot features (tag, onkopakko)

teekkari.py
Change the "tapan sut" text for now
Julius: hakemus "tapan sut" muutetaan muotoon "eii-kä"
Imneversorry: hyy-vä
=> ?? HAkemus

teekkari.py
Reverts Aivoapina/imneversorry#52
=> Revert "?? HAkemus"

teekkari.py
https://t.me/c/1363070040/88640
joku voi joskus lisätä tohon stikkerit, en ny jaksa
=> Implement pottiin vai kottiin

db.py, imneversorry.py, oppija.py, requirements.txt
Testataan tuotannossa
Muista pistää inlinemode päälle
=> Add fuzzy inline search for opis with @ImneversorryBot ?? query

teekkari.py
=> Added support for hakemsu, a new typo-based alternative to hakemus.

teekkari.py
Adds /kanye command to the bot which gets a Kanye West quote from https://api.kanye.rest/ and posts it to the channel.
=> Add kanye command

quotedle.py
this is needed for some reason
=> add dummy message handler to Quotedle (fixes tarot)

db.py, imneversorry.py, initdb.py, kissa.py
Its often difficult to keep track of which cat you are. This feature hopefully helps.
(Note that in the screenshots "imneversorry" is just a random user, not the bot)
=> Add kissa.py module for tracking which cat you are

teekkari.py
Infodumps by choosing a random Wikipedia article in Finnish or English and sending back a paragraph chosen at random therefrom.
=> Implement /gqqish feature

teekkari.py
Strips consonants and numbers before replacing last vowel with uli or something
=> nimuli with fancy regex

teekkari.py
```
?? siku_get
sikuget: sikugetin tullessa vitun-komento poistetaan botista, jos sikuget ei tule ennen wappua niin siku, sahrami ja liisa kiittävät kaikkia ja poistuvat ryhmästä. ks. myös vitun_siku sekä siku_get
```
=> Remove vitun

imneversorry.py, noppa.py
=> add noppa functionality

teekkari.py
tähän oli hakemus. Not pretty but it works
=> Add support to get helveten descriptions

valitsin.py
=> Allow "vai" options that are over 1 word each

teekkari.py
untested but it's python so what could go wrong
=> Enable vitun during opiskelijawappu and Christmas eve

valitsin.py
Reverts Aivoapina/imneversorry#87
=> Revert "Allow "vai" options that are over 1 word each"

kissa.py
=> Oon toi kissa

kilometri.py
New score multipliers more accurate in terms of energy expenditure.
=> Add swimming, rebalance score multipliers
